### PR TITLE
Added auto-collection support

### PR DESCRIPTION
**Pull request by GabeKnuth**
Added support for all games, favorites, and recent games collections.
Works on light and dark.

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @GabeKnuth, and thanks for the PR.

Probably this week I'll merge this. After that can you apply the same in the other branches we have? (`optimized`, `dark`, `dark-optimized`)

**Comment by GabeKnuth** [comment]
Do you want a separate PR for each? Also, is there anything special that has to be done to "optimize" these?

**Comment by HerbFargus** [comment]
I'm fine however so long as it works. As long as code is clean and consistent

**Comment by raelgc** [comment]
@GabeKnuth: yes, one PR for each, and for the ones with `optimized`, resize the images to `1280`.

**Comment by raelgc** [comment]
@HerbFargus: just thinking that maybe we should have just one branch, dark themed and optimized (due the Pi focus). Even on a PC, the difference between the full hd and the 1280p images are barely noticeable as they're only background images (but the RAM usage difference is huge).

In the last months I'm working in a dedicated detailed view for this theme, using variables, etc. Do you want that I send you some screenshots?

**Comment by HerbFargus** [comment]
I'm fine either way. Happy for you to take the reigns however you see fit

**Pull request merged**
